apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: config-default
  namespace: my-namespace 
beta.cloud.google.com/backend-config: '{"default": "config-default"}'
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: my-secret
